### ISSUE TITLE
[FEATURE] Update Tabs of Plugin when user selects a new version

### ISSUE THREAD

**Issue by bryanwhyte** [sonatype-nexus-community/nexus-iq-chrome-extension#100]
[zoom_0.mp4.zip](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/files/5343175/zoom_0.mp4.zip)

**Comment by ctownshend** [comment]
To do this, you can not simple put an anchor tag in with an href. That's because that changes the navigation of the popup and does not send a message to the background chrome app to navigate. You have to use
chrome.tabs.update({
    url: newURL,
  });
