### ISSUE TITLE
[BUG] Chrome extension suggests current version as remediation 

### ISSUE THREAD

**Issue by rseddon** [sonatype-nexus-community/nexus-iq-chrome-extension#111]
When there are no policy violations for the current version, the chrome plugin shows "remediation advice, upgrade to new version".  The version shown is the current version.  

This is rather confusing. If the current version has no violations, no remediation is needed.

**Comment by madpah** [comment]
@rseddon - appreciate this was raised a long time ago - but do you have an example component that demonstrates the behaviour reported?

**Comment by rseddon** [comment]
@madpah this was the URL used:  https://search.maven.org/artifact/org.springframework.boot/spring-boot-starter-test/2.3.2.RELEASE/jar
