### ISSUE TITLE
[FEATURE] Display Component Hygiene when available

### ISSUE THREAD

**Issue by bryanwhyte** [sonatype-nexus-community/nexus-iq-chrome-extension#112]
It would be helpful if the plugin provided detail on component hygiene (when available)

**Comment by ctownshend** [comment]
Fixed in 2.x
<dependency>
			<groupId>com.sparkjava</groupId>
			<artifactId>spark-core</artifactId>
			<version>2.7.0</version>
		</dependency>
		e.g. https://central.sonatype.com/artifact/com.sparkjava/spark-core/2.7.0

**Comment by madpah** [comment]
@maurycupitt - this may have been lost in v2.x.x - can you check?

**Comment by madpah** [comment]
Confirmed as implemented/fixed in v2.x.x.
