### ISSUE TITLE
[FEATURE] make the extension compatible with Firefox

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/nexus-iq-chrome-extension#13]
did a first try using about:debugging as explained on https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

got issues with:
- "declarativeContent" permission: https://stackoverflow.com/questions/39252384/is-there-a-ff-equivalent-to-chrome-declarativecontent-onpagechanged
- "background": https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Compatibilit%C3%A9_du_navigateur
- "options_page": deprecated, replaced with "options_ui" https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_page

**Comment by madpah** [comment]
Firefox/Mozilla has adopted Event-driven background scripts and does not support service workers 😵‍💫 

See https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/
