### ISSUE TITLE
[DOC] Ensure README is up to date

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/nexus-iq-chrome-extension#131]
Update readme for first timers.
yarn start -> fails -> "error Command "start" not found."
yarn requires npm 12
yarn Build
Debug mode for Chrome extensions -> load unpacked

**Comment by madpah** [comment]
README has been re-written with new images and content for the 2.0.0 release 48eab2825ac13d67723adce82bbc77d0051cdcee
