### ISSUE TITLE
Add policy support for IQ Server Scan

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/nexus-iq-chrome-extension#133]
If someone is using IQServer then show policy violation.

**Comment by DarthHater** [comment]
How would they have a policy? It's a single library. Do you know of an endpoint where we can run a scan of one component against policy? I think I know of one, just asking questions.

**Comment by DarthHater** [comment]
This API can be used: https://help.sonatype.com/iqserver/automating/rest-apis/component-evaluation-rest-apis---v2

**Comment by ctownshend** [comment]
version 2.x supports policy
