### ISSUE TITLE
parse  mvnrepository.com

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/nexus-iq-chrome-extension#148]
Legacy Chrome Extension could parse https://mvnrepository.com/artifact/org.apache.struts/struts2-core/2.2.3
New one needs this function as well
Expected Behaviour: Navigate to https://mvnrepository.com/artifact/org.apache.struts/struts2-core/2.2.3 and recive security alerts
Actual behaviour: Page hangs

**Comment by madpah** [comment]
Confirmed this is working now in v2.x.x on #260.

![Screenshot 2023-05-19 at 13 08 38](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/4b67ed9c-6991-41bf-80be-c47f4f14cbe4)
