### ISSUE TITLE
[FEATURE] Include remediation advice

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/nexus-iq-chrome-extension#166]
Remediation tab with

1. [x] Recommended version based on policy
2. [x] Version History graph
3. [ ]  Clickable version on version history tab and navigate to this version

**Comment by maurycupitt** [comment]
@ctownshend - the clickable version is what I need help with.  

https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/blob/38e2f4b175d929d4ac65713bb6bce6f61b5ccae6/src/components/Popup/IQServer/RemediationPage/RemediationDetails/RemediationDetails.tsx#L67

**Comment by madpah** [comment]
@maurycupitt - can you please confirm here if the FEATURE request as written is already covered on the v2.x.x branch?

FYI @ctownshend

**Comment by madpah** [comment]
Third point now confirmed as addressed in v2.x.x branch.
