### ISSUE TITLE
[BUG] Plugin broken when browsing PyPi.org?

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/nexus-iq-chrome-extension#170]
A number of people have reported issues using the Chrome Plugin on pypi.org.

Here is an example with Developer Tools open showing a JS error:

![Screenshot 2022-02-02 at 15 04 08](https://user-images.githubusercontent.com/10280392/152179949-5a9263db-f947-41e4-9cd6-a9cff71c66c7.png)

Chrome Version: 97.0.4692.99 (Official Build) (x86_64)
Nexus Chrome Plugin Version: 1.9.4

FYI @DarthHater / @bhamail / @ctownshend

**Comment by maurycupitt** [comment]
This is a quick fix - #171
