### ISSUE TITLE
[BUG]: Login button does not validate correctly

### ISSUE THREAD

**Issue by ctunited15** [sonatype-nexus-community/nexus-iq-chrome-extension#196]
Clicking the login, gives the message "Login Successful", but when saving, it errors out.  It is easy to test by entering the wrong username / pw.  

The problem is that I am already logged in and the cookie is still there. It should be invalidated.

**Comment by madpah** [comment]
There is definitely some issue in this space still on v2.x.x branch @maurycupitt.

We do not allow empty fields 👍 , but invalid login information does not provide any user feedback or errors?

![Screenshot 2023-05-19 at 13 26 17](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/c098a99f-a778-4d87-89aa-865fa439851e)

![Screenshot 2023-05-19 at 13 26 48](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/b9afb7d5-805a-4db2-b79f-e721a48e315f)

**Comment by madpah** [comment]
Turns out that because this call is to an internal `/rest` API, it uses COOKIE if it is there and avoids the actual credentials enters.

Looks like #267 now becomes more important...

**Comment by madpah** [comment]
Resolved now in v2.x.x branch.
