### ISSUE TITLE
[BUG]: handle @ in component name or namespace

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/nexus-iq-chrome-extension#198]
e.g. https://www.npmjs.com/package/@sonatype/policy-demo is component unknown due to the @
Similarly
pkg:npm/%40angular/animation@12.3.1
Need to encode the @ as %40 for valid purl

**Comment by madpah** [comment]
This is confirmed as fixed in v2.x.x for the example provided.

![Screenshot 2023-05-19 at 13 22 14](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/29ebd556-57e9-49ab-87ba-e03606a18fff)
