### ISSUE TITLE
OSSIndex when IQ isn't available

### ISSUE THREAD

**Issue by CMYanko** [sonatype-nexus-community/nexus-iq-chrome-extension#2]
might be nice and more community friendly if we could redirect all request to OSSIndex if an IQ Server hasn't been configured.

**Comment by ctownshend** [comment]
Will not fix this as Chrome Extension should only work with Sonatype Nexus Lifecycle. The intention is that this extension is for paying customers only. The plugin does use OSSIndex for those eco-systems that are not in Lifecycle e.g. PHP. However this is in addition to Lifecycle and not a replacement for lifecycle.
