### ISSUE TITLE
Request failed with status code 402

### ISSUE THREAD

**Issue by mkey-cdx** [sonatype-nexus-community/nexus-iq-chrome-extension#20]
When trying to connect the chrome plugin to iq-server instance, we get a 402 error (Payment Required). Note that we use a valid IQ-server Lifecycle licence and that we could connect the jenkins plugin with no error.
![image](https://user-images.githubusercontent.com/22774947/61364693-a3480180-a886-11e9-9b3c-4653770579be.png)

This happens right after setting login credentials on the plugin settings page. We got a  'Login successful when clicking on 'Login' button but we cannot select any application.

**Comment by ctownshend** [comment]
Hi mkey-cdx, apologies for the delay. How did you go, is this sorted?

**Comment by mkey-cdx** [comment]
Thanks for your response. It appears that our licence does not support the chrome extension actually.
I close this issue.
