### ISSUE TITLE
Using MVN Repo, vulnerabilities on not identified on latest components in list of component versions

### ISSUE THREAD

**Issue by caw916** [sonatype-nexus-community/nexus-iq-chrome-extension#200]
Using the MVN Repository, I get a list of the versions of the SnakeYAML component.  the latest 2 versions don't show vulnerabilities in the list but if I go to the component itself the plugin shows vulnerabilities. 
![IQ Chrome Extension bug - MVN Repo not identifying  vulnerabilites on latest components in list](https://user-images.githubusercontent.com/48732989/210873763-e3872e34-a598-49a5-872c-3dcb5ab18df8.JPG)

**Comment by ctownshend** [comment]
OK, so the vulnerability flag in the datagrid, was due to a collision on a css selector. We use "vuln" and so does mvnrepository. So the fix is to make the Sonatype plugin to use a more specific selector so it doesn't collide. now using "sonatype-iq-extension-vuln"
