### ISSUE TITLE
test: confirm support for NuGet https://www.nuget.org

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/nexus-iq-chrome-extension#219]
Confirm support in 2.0.0.

- [x] Does it work for this URL / Package Registry?
- [x] Are the docs correct?

Raise new tickets for anything not working / needs updating in docs.

**Comment by nathancarv** [comment]
**Tested with JMeter 5.4.1: https://www.nuget.org/packages/JMeter/5.4.1**

<img width="1716" alt="Screen Shot 2023-03-08 at 9 55 01 PM" src="https://user-images.githubusercontent.com/48229758/223905144-2ee6a4c4-944b-4f24-aaac-a0f13c0019e7.png">

The chrome extension tool stops working whenever the URL gets updated with additional text following the "#".

**Comment by maurycupitt** [comment]
@nathancarv - Could you just double check the fix - thanks.

**Comment by nathancarv** [comment]
> @nathancarv - Could you just double check the fix - thanks.

Pulled in the changes and can confirm that the above behavior has been corrected.

This ticket has been resolved. ✅

**Comment by nathancarv** [comment]
@maurycupitt I noticed that adding a "/" at the end of the URL causes the extension not to work, while the older chrome extension still does:
![image](https://user-images.githubusercontent.com/48229758/228065578-aeee5930-3d5b-499f-b124-1e844f7de5f0.png)

**Comment by madpah** [comment]
Fix for trailing slash added in #260.

Discovered #262 whilst testing.

**Comment by madpah** [comment]
![Screenshot 2023-05-19 at 10 24 01](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/47058a91-1947-420e-a44d-80a86b665e89)
