### ISSUE TITLE
test: confirm support for Golang – Go – https://search.gocenter.io/

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/nexus-iq-chrome-extension#226]
Confirm support in 2.0.0.

- [ ] Does it work for this URL / Package Registry?
- [ ] Are the docs correct?

Raise new tickets for anything not working / needs updating in docs.

**Comment by acpcreation** [comment]
gocenter.io has been shut down. Ref: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
