### ISSUE TITLE
test: confirm support for Java – Maven – https://repo.spring.io/list/

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/nexus-iq-chrome-extension#229]
Confirm support for 2.0.0

**Comment by ctownshend** [comment]
The https://repo.spring.io/list/ is a maven repo hosted on artifactory. So you will have to test using the artifactory parser. I have noticed that Artifactory has changed their URL pattern, so you will need to recheck the url pattern and test that. I don't think we have implemented this code in v2 yet.
