### ISSUE TITLE
test: confirm support for PHP – Packagist/composer – https://packagist.org/

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/nexus-iq-chrome-extension#233]
Confirm support in 2.0.0.

- [x] Does it work for this URL / Package Registry?
- [ ] Are the docs correct?

Raise new tickets for anything not working / needs updating in docs.

**Comment by nathancarv** [comment]
**Tested with:** https://packagist.org/packages/laravel/laravel
The Chrome extension works as expected:
<img width="1635" alt="Screen Shot 2023-05-01 at 9 46 17 PM" src="https://user-images.githubusercontent.com/48229758/235562099-10a95764-dabf-4793-9942-815a503a0ca2.png">

**Comment by madpah** [comment]
![Screenshot 2023-05-19 at 11 33 04](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/c7019dcd-0260-47c2-8c4c-f778cb6b6c24)
![Screenshot 2023-05-19 at 11 33 23](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/6f382bc6-2305-4e56-b7fd-08bde323d492)

Working fine on #260.
