### ISSUE TITLE
test: confirm support for Ruby – RubyGems – https://rubygems.org/

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/nexus-iq-chrome-extension#236]
Confirm support in 2.0.0.

- [ ] Does it work for this URL / Package Registry?
- [ ] Are the docs correct?

Raise new tickets for anything not working / needs updating in docs.

**Comment by nathancarv** [comment]
**Testing with https://rubygems.org/gems/olabini-log4j**
The chrome extension doesn't register at this page when the version isn't in the URL. However, it notices the component in the older extension version:
<img width="1192" alt="Screen Shot 2023-03-09 at 4 45 48 PM" src="https://user-images.githubusercontent.com/48229758/224168165-543d2c3f-4b6a-4947-b0ff-041c850ccabc.png">

The updated chrome extension will work once the version is the URL:
<img width="1194" alt="Screen Shot 2023-03-09 at 4 51 15 PM" src="https://user-images.githubusercontent.com/48229758/224168588-ce6d38af-725a-4b3a-a4d9-fd494c5b6d93.png">

**Comment by nathancarv** [comment]
Pulled in the latest changes and the extension will now work without the version in the URL.

However, I noticed that when there is a slash at the end of the URL (https://rubygems.org/gems/olabini-log4j/), the extension does not work:
![image](https://user-images.githubusercontent.com/48229758/228064834-08e83c98-828d-43f4-8dea-e64aaac1d634.png)

**Comment by madpah** [comment]
Re-test on #260 shows this is now working.

![Screenshot 2023-05-19 at 11 42 43](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/39cf16c6-557b-40cf-8ae5-9a2f9f3d9d9c)
![Screenshot 2023-05-19 at 11 43 21](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/60e7c1f4-1bf9-4c94-aff0-7e3405de3440)
