### ISSUE TITLE
bug: handle extra path after the version in URL

### ISSUE THREAD

**Issue by maurycupitt** [sonatype-nexus-community/nexus-iq-chrome-extension#242]
Handle the extra path after the version in the URL

Examples:
- https://www.npmjs.com/package/es5-ext/v/0.10.52?activeTab=versions
- https://central.sonatype.com/artifact/org.apache.logging.log4j/log4j-core/2.6.2/overview

**Comment by maurycupitt** [comment]
@ctownshend - this falls into the PageParsing help that I need.  Would you be able to tackle this as well?

**Comment by madpah** [comment]
This is fixed by #260.
