### ISSUE TITLE
Prevent package-lock.json from getting renamed to npm-shrinkwrap.json

### ISSUE THREAD

**Issue by roger-lau** [sonatype-nexus-community/nexus-iq-chrome-extension#25]
When the plugin executes npm shrinkwrap, the package-lock.json file in the project is renamed to npm-shrinkwrap.json. That causes inconveniences to our build pipeline. 
In your future release, would you consider keeping the package-lock.json file?

The preferred behaviour of the plugin would be not changing the original files in my project.

**Comment by ctownshend** [comment]
@roger-lau you have raised this issue against the chrome extension project, it should be against the VSCode plugin. I will close this one. Can you raise it in the vscode project? https://github.com/sonatype-nexus-community/vscode-iq-plugin
