### ISSUE TITLE
[BUG] trailing "/" on the end of the iq server url causes error

### ISSUE THREAD

**Issue by acpcreation** [sonatype-nexus-community/nexus-iq-chrome-extension#251]
In the extension options, in the IQ Server URL input field, submitting http://localhost:8070/ causes error on the component webpages because of the trailing "/" at the end. Only works when "/" at the end is removed ( ex: http://localhost:8070 )

Should work with either URL input. ( http://localhost:8070 or http://localhost:8070/ )

**Comment by madpah** [comment]
Resolved in #271.
