### ISSUE TITLE
[ISSUE] User Credentials stored in local browser storage

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/nexus-iq-chrome-extension#3]
The initial release 1.7.5 stores your username and password in plain text in Chrome storage. This is a known issue at this time. We are investigating solutions.

**Comment by hboutemy** [comment]
see #28 consider "Component Evaluator" role

**Comment by madpah** [comment]
Appears that this is a known issue with extensions: http://blog.elliottkember.com/chromes-insane-password-security-strategy

**Comment by madpah** [comment]
There is no known workaround to safely store credentials in Chrome Extensions at this time.
