### ISSUE TITLE
Hitting login multiple times on the config screen adds to app list each time

### ISSUE THREAD

**Issue by ButterB0wl** [sonatype-nexus-community/nexus-iq-chrome-extension#67]
![image](https://user-images.githubusercontent.com/37317224/73617145-baafc780-45e9-11ea-8b50-ec3992378395.png)

Every time I hit 'login' the list gets bigger here and appends the list of apps to the previously populated list

**Comment by ctownshend** [comment]
Hi @ButterB0wl , can confirm this in 1.18. I have a fix for you coming out soon.
