### ISSUE TITLE
can't search for @angular/animations NPM package

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/nexus-iq-chrome-extension#7]
when browsing https://www.npmjs.com/package/@angular/animations/v/6.1.10 , component name and version are not recognized

**Comment by ctownshend** [comment]
Will be fixed in next release (1.7.8). Issue is due to '/' in the name, I use the slash to parse the component name and version. Did not handle / in the name of a component. Have added this now.

**Comment by ctownshend** [comment]
Herve this is release in 1.7.8 today.

**Comment by hboutemy** [comment]
just tested, works like a charm, thank you
