### ISSUE TITLE
Information panel never loads for components from https://packagist.org

### ISSUE THREAD

**Issue by StuBishop** [sonatype-nexus-community/nexus-iq-chrome-extension#78]
<img width="1667" alt="Screenshot 2020-03-31 at 10 32 58" src="https://user-images.githubusercontent.com/51403913/78021483-3a88b280-734b-11ea-882c-229a8247eca2.png">

You get the attached error when trying to display the component information for:-
https://packagist.org/packages/lodash-php/lodash-php

**Comment by ctownshend** [comment]
Bug in OSSIndex evaluation.  Missing url parameter. Fixed.
