### ISSUE TITLE
Information panel does not load, hexagon keep spinning when csrfProtection: false in .yml 

### ISSUE THREAD

**Issue by JoCosta** [sonatype-nexus-community/nexus-iq-chrome-extension#79]
When csrfProtection: false in the config.yml, component information panel never loads and instead the hexagon keeps spinning.
Note that csrfProtection being disabled is a mandatory requirement for the IQ Server setup to work which involves an Apache Common Gateway Interface.

**Comment by ctownshend** [comment]
Issue is to do with checking for cookies. If csrfProtection is off in the config.yml, then the cookie check fails and returns undefined. Later code doesn't handle this case. So adding code to check for no cookie then attempt to create one on the fly. This is required by the APIs now.
