### ISSUE TITLE
[BUG] unrecognized Packagist Composer component

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/nexus-iq-chrome-extension#99]
looking at https://packagist.org/packages/paragonie/random_compat#v1.4.0

should display vulnerability https://ossindex.sonatype.org/component/pkg:composer/paragonie/random_compat

and perhaps displayed Package should be "paragonie/random_compat" (ie vendor/package) instead of only "random_compat" (ie package only, without vendor)

**Comment by madpah** [comment]
This appears to be resolved in v2.x.x version on #260 

![Screenshot 2023-05-19 at 13 10 43](https://github.com/sonatype-nexus-community/nexus-iq-chrome-extension/assets/10280392/49135a2b-9b37-404c-a6dc-4df77d62c8a1)
